version: "3"

services:
  food_db:
    build:
      context: ./food_db
    image: food/db
    container_name: food_db
    env_file: .env
    volumes:
      - "../data:/tmp/raw-data"
    ports:
      - "5434:5432"

  bastion:
    build:
      context: ./bastion
    image: tutorial/bastion
    container_name: tutorial_bastion
    #working_dir: /app
    command: bash
    #user: ${UID}:${GID}
    tty: true
    env_file: .env
    environment:
      FOOD_DB_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@food_db/food'
    volumes:
      - "../data:/data"
      - "../src:/code"


  # reverseproxy:
  #   build:
  #     context: ./reverseproxy
  #   image: tutorial/reverseproxy
  #   container_name: tutorial_reverseproxy
  #   depends_on:
  #     - api
  #   ports:
  #     - 8090:8090
  #     - 8081:8081

  # api:
  #   build:
  #     context: ./api
  #   image: tutorial/api
  #   container_name: tutorial_api
  #   volumes:
  #     - "./api:/app"
  #   ports:
  #     - "5000:5000"


  # tyra:
  #   build:
  #     context: ./tyra
  #   image: tutorial/tyra
  #   container_name: tutorial_tyra
  #   env_file: .env
  #   ports:
  #     - "5001:5001"
