version: "3"

services:
  db:
    build:
      context: ./db
    image: citibike/db
    container_name: citibike_db
    env_file: ../.env
    volumes:
      - "../data:/tmp/raw-data"
    ports:
      - "5433:5432"

  bastion:
    build:
      context: ./bastion
    image: citibike/bastion
    container_name: citibike_bastion
    #working_dir: /app
    command: bash
    environment:
      DB_URL: 'postgres://db:5432'
      REDIS_URL: 'redis://redis:6379'
      RABBITMQ:URL:  ''

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'

  redis:
    image: redis
    ports:
      - '6379:6379'

  reverseproxy:
    build:
      context: ./reverseproxy
    image: citibike/reverseproxy
    container_name: citibike_reverseproxy
    depends_on:
      - api
    ports:
      - 8090:8090
      - 8081:8081

  api:
    build:
      context: ./api
    image: citibike/api
    container_name: citibike_api
    volumes:
      - "./api:/app"
    ports:
      - 5000
